require("prototypes.technology")
require("prototypes.style")
require("prototypes.signals")
require("prototypes.sprites")
require("prototypes.sprites")
require("prototypes.inputs")
require("prototypes.in-world-selector")